version: '3'
services:
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8005:8000"
    volumes:
      - ~/mkdocs/:/docs
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs.rule=Host(`ruesworld`)"
      - "traefik.http.routers.mkdocs.entrypoints=web"
      - "traefik.http.services.mkdocs.loadbalancer.server.port=8000"
