site_name: Xavier's Docs
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  #   - social
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true


nav:
  - Home: https://example.com
  - Knowledge Base:
      - kb/index.md
      - "Start Here": index.md
      - Networks:
          - networks/index.md
      - Ansible:
          - ansible/index.md
          - Ad-Hoc: ansible/Ad_Hoc.md
      - Docker:
          - docker/index.md
          - Architecture: docker/architecture.md
          - Basics: docker/basics.md
      - Kubernetes:
          - CKAD:
              - kubernetes/ckad/index.md
              - 3 - Understanding Kubernetes:
                - kubernetes/ckad/3_Understanding_Kubernetes/3_1_CNC.md
                - kubernetes/ckad/3_Understanding_Kubernetes/3_2_how_k8s_enables_cncf.md
                - kubernetes/ckad/3_Understanding_Kubernetes/3_5_k8s_architecture.md
                - kubernetes/ckad/3_Understanding_Kubernetes/3_6_essential_api_resources.md
              - 5 - Pod Basic Features:
                - kubernetes/ckad/5_Pod_Basic_Features/5_1_Options.md
                - kubernetes/ckad/5_Pod_Basic_Features/5_2_Pod_Structure_And_Use.md
                - kubernetes/ckad/5_Pod_Basic_Features/5_3_Pods_The_DevOps_Way.md
                - kubernetes/ckad/5_Pod_Basic_Features/5_4_Generating_YAML_Files.md
      - Python:
          Flask:
            - Baiscs: python/Flask/Basics.md
          Requests:
            - python/requests/json_vs_data.md


